### ISSUE TITLE
A problem occurred configuring project ':serious_python_android'.

### ISSUE THREAD

**Issue by fckfck97** [flet-dev/serious-python#101]
I have everything installed, I followed the steps at https://flet.dev/docs/publish/android/ before the update it compiled fine but after I did not install android studio koala sdk and ndk from the command line.

           Got dependencies!
           11 packages have newer versions incompatible with dependency constraints.
           Try `flutter pub outdated` for more information.

           Running Gradle task 'assembleRelease'...
           Running Gradle task 'assembleRelease'...                         2,037ms

           FAILURE: Build completed with 2 failures.

           1: Task failed with an exception.
           -----------
           * What went wrong:
           A problem occurred configuring project ':serious_python_android'.
           > [CXX1101] NDK at /Users/jesusdelgado/Library/Android/sdk/ndk/25.1.8937393
           did not have a source.properties file

           * Try:
           > Run with --stacktrace option to get the stack trace.
           > Run with --info or --debug option to get more log output.
           > Run with --scan to get full insights.
           > Get more help at https://help.gradle.org.
           ============================================================================
           ==

           2: Task failed with an exception.
           -----------
           * What went wrong:
           Failed to query the value of property 'buildFlowServiceProperty'.
           > Could not isolate value
           org.jetbrains.kotlin.gradle.plugin.statistics.BuildFlowService$Parameters_De
           corated@62c731e5 of type BuildFlowService.Parameters
              > A problem occurred configuring project ':serious_python_android'.
                 > [CXX1101] NDK at
           /Users/jesusdelgado/Library/Android/sdk/ndk/25.1.8937393 did not have a
           source.properties file

           * Try:
           > Run with --stacktrace option to get the stack trace.
           > Run with --info or --debug option to get more log output.
           > Run with --scan to get full insights.
           > Get more help at https://help.gradle.org.
           ============================================================================
           ==

           BUILD FAILED in 1s
           Gradle task assembleRelease failed with exit code 1

           Error building Flet app - see the log of failed command above.
           
My Flutter installations compile the ipa excellently. I have a mac m1. It was difficult for me to compile the ipa.

    flutter doctor -v
    [✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale es-419)
        • Flutter version 3.22.2 on channel stable at
          /Users/jesusdelgado/development/flutter
        • Upstream repository https://github.com/flutter/flutter.git
        • Framework revision 761747bfc5 (3 weeks ago), 2024-06-05 22:15:13 +0200
        • Engine revision edd8546116
        • Dart version 3.4.3
        • DevTools version 2.34.3
    
    [✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
        • Android SDK at /Users/jesusdelgado/Library/Android/sdk
        • Platform android-34, build-tools 34.0.0
        • Java binary at: /Applications/Android
          Studio.app/Contents/jbr/Contents/Home/bin/java
        • Java version OpenJDK Runtime Environment (build
          17.0.10+0-17.0.10b1087.21-11609105)
        • All Android licenses accepted.
    
    [✓] Xcode - develop for iOS and macOS (Xcode 15.4)
        • Xcode at /Applications/Xcode.app/Contents/Developer
        • Build 15F31d
        • CocoaPods version 1.15.2
    
    [✓] Chrome - develop for the web
        • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
    
    [✓] Android Studio (version 2024.1)
        • Android Studio at /Applications/Android Studio.app/Contents
        • Flutter plugin can be installed from:
          🔨 https://plugins.jetbrains.com/plugin/9212-flutter
        • Dart plugin can be installed from:
          🔨 https://plugins.jetbrains.com/plugin/6351-dart
        • Java version OpenJDK Runtime Environment (build
          17.0.10+0-17.0.10b1087.21-11609105)
    
    [✓] VS Code (version 1.86.0)
        • VS Code at /Users/jesusdelgado/Downloads/Visual Studio Code.app/Contents
        • Flutter extension can be installed from:
          🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
    
    [✓] Connected device (3 available)
        • macOS (desktop)                 • macos                 • darwin-arm64   • macOS
          14.5 23F79 darwin-arm64
        • Mac Designed for iPad (desktop) • mac-designed-for-ipad • darwin         • macOS
          14.5 23F79 darwin-arm64
        • Chrome (web)                    • chrome                • web-javascript • Google
          Chrome 126.0.6478.127
    
    [✓] Network resources
        • All expected network resources are available.
    
    • No issues found!

**Comment by jjjunehkim** [comment]
I got same problem!
Can you explain how to solve the problem?

**Comment by bagusindrayana** [comment]
> I got same problem! Can you explain how to solve the problem?

try delete "25.1.xxx" folder from ndk folder, check error log to find which folder
