### ISSUE TITLE
Error during `flet build` when requirements.txt contains empty lines or comments

### ISSUE THREAD

**Issue by allieus** [flet-dev/serious-python#102]
## Description

When running the `flet build` command, an error occurs if the `requirements.txt` file in the project contains empty lines. This results in an `ERROR: Invalid requirement: ''` message, preventing the successful packaging of the Flet application.

<img width="1790" alt="image" src="https://github.com/user-attachments/assets/b24887f4-7ef3-4c1a-8405-2df2720ec21b">

**Note: Removing all empty lines from `requirements.txt` allows the build to complete successfully.** 

<img width="1016" alt="image" src="https://github.com/user-attachments/assets/094738f3-e330-4491-ae69-484615928e12">

### Reproduction Steps

1. Create a Flet project with a `requirements.txt` file.
2. Add one or more empty lines between package names in `requirements.txt`.

last line is empty.

```
flet==0.23.2

```

3. Run the `flet build` command.
4. Observe the error message: `ERROR: Invalid requirement: ''`

**Comment by ndonkoHenri** [comment]
Will be fixed along with https://github.com/flet-dev/flet/issues/3596
