### ISSUE TITLE
Getting error when starting app 

### ISSUE THREAD

**Issue by USER4247** [flet-dev/serious-python#105]
Restarted application in 1,603ms.
E/flutter (18467): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PathNotFoundException: Getting current working directory failed, path = '' (OS Error: No such file or directory, errno = 2)
E/flutter (18467): #0      _uriBaseClosure (dart:io-patch/directory_patch.dart:75:5)
E/flutter (18467): #1      Uri.base (dart:core-patch/uri_patch.dart:21:41)
E/flutter (18467): #2      Style._getPlatformStyle (package:path/src/style.dart:41:13)
E/flutter (18467): #3      Style.platform (package:path/src/style.dart:33:33)
E/flutter (18467): #4      Style.platform (package:path/src/style.dart)
E/flutter (18467): #5      new Context._internal (package:path/src/context.dart:49:23)
E/flutter (18467): #6      createInternal (package:path/src/context.dart:14:37)
E/flutter (18467): #7      context (package:path/path.dart:58:25)
E/flutter (18467): #8      context (package:path/path.dart)
E/flutter (18467): #9      extension (package:path/path.dart:205:5)
E/flutter (18467): #10     SeriousPython.run (package:serious_python/serious_python.dart:44:14)
E/flutter (18467): #11     main (package:unilinkd/main.dart:46:23)
E/flutter (18467): #12     _runMain.<anonymous closure> (dart:ui/hooks.dart:301:23)
E/flutter (18467): #13     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
E/flutter (18467): #14     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

I am using emulator

**Comment by ndonkoHenri** [comment]
Will you mind providing more context to your issue?
