### ISSUE TITLE
Upgrade Python to 3.12.6

### ISSUE THREAD

**Issue by kentbull** [flet-dev/serious-python#110]
Python 3.12 is being used for a fair number of libraries and staying on Python 3.12 breaks builds that require packages of only 3.11 and down.

This (https://github.com/flet-dev/serious-python/pull/109) draft PR starts the process, though it will be a fair bit of work to upgrade serious-python and all other related dependencies to Python 3.12.

I picked Python 3.12.6 because it's the latest build right now and some of the referenced dependencies in the PR already support it.

See [this](https://github.com/flet-dev/flet/issues/4007) issue for an example of the `type` feature in 3.12 that someone wants to use in Flet that would be enabled by this upgrade.

This may fix the following issue: https://github.com/flet-dev/flet/issues/4007

**Comment by FeodorFitsner** [comment]
serious_python 0.8.0 uses python 3.12.6
