### ISSUE TITLE
Package fained using official code

### ISSUE THREAD

**Issue by RalphGuo** [flet-dev/serious-python#118]
I'm going to package python libs using official code:
![image](https://github.com/user-attachments/assets/1d1fed6c-63a3-4911-bff4-e8c20af1b502)
but error occured as followed 
![image](https://github.com/user-attachments/assets/fda58602-48db-4221-abed-af8310806a84)
those Chinese word indicates :missing parameter in parameter list.

If I manually define the libs I need, it workd well.
```
dart run serious_python:main package app/src -p Windows --requirements 'numpy,lru-dict' --verbose
```
What change can I make to package libs from requirements.txt?

**Comment by markm812** [comment]
You are running on Windows, try wrapping your requirements args with single quotes like this.
```
dart run serious_python:main package app/src -p Android --requirements '-r,app/src/requirements.txt' 
```

**Comment by RalphGuo** [comment]
> You are running on Windows, try wrapping your requirements args with single quotes like this.
> 
> ```
> dart run serious_python:main package app/src -p Android --requirements '-r,app/src/requirements.txt' 
> ```

Thanks a lot! I changed your code like below in VSCode and it worked!
```
dart run serious_python:main package app/src -p Android --requirements '-rapp/src/requirements.txt' --verbose
```
there is no space between '-r' and 'app' for unknown reason, but it do work. :P
