### ISSUE TITLE
flet build to apk error in ndk

### ISSUE THREAD

**Issue by zox47** [flet-dev/serious-python#13]
im trying to build my apk with "flutter build apk --release" but i get this errors and also i get apk but its stuck in load spining
![Screenshot 2023-08-05 180552](https://github.com/flet-dev/serious-python/assets/53087330/62673b74-81f8-483d-877b-8205d0b16fb3)

**Comment by zox47** [comment]
OS: kali linux

**Comment by FeodorFitsner** [comment]
Those should be treated as warnings.

**Comment by zox47** [comment]
> treated as warnings.

and please whats the solution

**Comment by FeodorFitsner** [comment]
I mean it should complete building APK or AAB despite those errors.

**Comment by zox47** [comment]
> I mean it should complete building APK or AAB despite those errors.

yeah its completed but wwhen i get the apk this whats i get when run it in my android

![Screenshot_2023-08-04-23-22-59-864_com example flet_example](https://github.com/flet-dev/serious-python/assets/53087330/211033dd-e24f-4164-a38d-12f5a346e03f)

nothing showin after thats

**Comment by FeodorFitsner** [comment]
Make sure you are using the latest version of `serious_python` package. Try running on simulator and see if there are any errors.

**Comment by zox47** [comment]
> Make sure you are using the latest version of `serious_python` package. Try running on simulator and see if there are any errors.

ok thanks i will do that

**Comment by certainlyWrong** [comment]
I had a similar issue with Flask Example. I can compile, but the app unexpectedly quits on startup.

**Comment by zox47** [comment]
> Make sure you are using the latest version of `serious_python` package. Try running on simulator and see if there are any errors.

I found the issues was the latest of flet version and when i back to old version like 0.8.4 its work soo the solution is work with old version of flet

**Comment by FeodorFitsner** [comment]
What errors did you get with SP 0.2.3 and Flet 0.9.0?

**Comment by zox47** [comment]
> What errors did you get with SP 0.2.3 and Flet 0.9.0?

when i convert it to apk its give me an apk but with load anything but when i use the debug mode i think its an error about socks server or somthing
