### ISSUE TITLE
Is it possible to read the script output?

### ISSUE THREAD

**Issue by DavideCampagna** [flet-dev/serious-python#14]
```
await SeriousPython.run(
      'pyScripts/summarize.py',
      appFileName: 'summarize.py',
      environmentVariables: {'text': text},
      sync: true
    );
```

The script is ran with the code above. Is it possible to read and monitor from dart the script output print?

**Comment by FeodorFitsner** [comment]
Are you running on iOS or Android?

**Comment by DavideCampagna** [comment]
Hi, both of them.
I’m developing an app for both iOS and Android.
Basically, at needed time I need to run specific python scripts to do basic elaboration.
For example, this summarize.py get as an input a String, summarize it using an ML pretrained model and prints the summarized string.
I want to retrive the summarized string 😁
Is it possible?
Anyway, thank you for you support 😁

**Comment by FeodorFitsner** [comment]
Hi Davide,

I see at least two options:

1) Using `in.txt` and `out.txt` files to input some data to a Python program and get results. Create `in.txt` in Dart with input, run Python which reads `in.txt` and puts output to `out.txt`, read `out.txt` in Dart.
2) Establish a socket (UDS) server in Dart and connect it from Python.

Let me know what you think.

**Comment by DavideCampagna** [comment]
Hi!
Thank you 😀 
At the end I decided to build a flask app as a backend accessed via API bi the dart code.
What do you think about this approach?

**Comment by FeodorFitsner** [comment]
Yeah, sounds good. Flask backend is in one of the examples: https://github.com/flet-dev/serious-python/tree/main/example/flask_example

**Comment by DavideCampagna** [comment]
Thank you 😁
