### ISSUE TITLE
python runs fine on android, but i don't know how can i add 3rd party libraries

### ISSUE THREAD

**Issue by du9ngtdh** [flet-dev/serious-python#15]
python runs fine on android, but i don't know how can i add 3rd party libraries

**Comment by FeodorFitsner** [comment]
What libraries specifically you'd like to add?

**Comment by SKbarbon** [comment]
> python runs fine on android, but i don't know how can i add 3rd party libraries

@du9ngtdh Try updating the requirements.txt file in src

**Comment by du9ngtdh** [comment]
> Những thư viện cụ thể bạn muốn thêm?

i want to add the libraries numpy, opencv, ...
chaquopy does provide a repository of libraries, but most of them are only for python3.8, I'd be grateful if you could provide more options serious_python python3.8

**Comment by Hindrich0815** [comment]
Hi, i am struggeling with the same problem.
For example adding 'plyer' to requirement.txt and using it in main.py works fine but adding 'numpy==1.24.2' leads to a SocketError (No such file or directory).

**Comment by du9ngtdh** [comment]
> Hi, i am struggeling with the same problem.
> For example adding 'plyer' to requirement.txt and using it in main.py works fine but adding 'numpy==1.24.2' leads to a SocketError (No such file or directory) while running the app.

on android you can use C extensions package like numpy, cv2, tflite, pandas, tensoflow, pytouch... the thing to do is use python3.8.  The picture above is an example

![Screenshot_2023-08-27-17-54-45-086_com.example.example.jpg](https://github.com/flet-dev/serious-python/assets/103344064/48fd3d4e-8fa3-4a6e-9358-a2557ee1b535)

**Comment by du9ngtdh** [comment]
It's a pity that flet_embed (for mobile) doesn't work directly with chaquopy.  I can integrate chaquopy's python3.8 into Serious_python.  and it is compatible with flet.  First we need to modify the Py_Initialized() function, we will initialize python3.8 with setenv to set the PYTHONPATH with Flutter ffi.  DynamicLibrary.open files.so supports Numpy's library.  also build .py files using python3.8 on chaquopy.  There's so much to do that it's hard to give complete instructions

**Comment by certainlyWrong** [comment]
> It's a pity that flet_embed (for mobile) doesn't work directly with chaquopy. I can integrate chaquopy's python3.8 into Serious_python. and it is compatible with flet. First we need to modify the Py_Initialized() function, we will initialize python3.8 with setenv to set the PYTHONPATH with Flutter ffi. DynamicLibrary.open files.so supports Numpy's library. also build .py files using python3.8 on chaquopy. There's so much to do that it's hard to give complete instructions

I also believe that the way the Python application is loaded is not ideal. Attaching the app.zip to the APK makes it very heavy, depending on the dependencies we intend to use. Perhaps enabling the loading of applications from cache or another directory could bring more flexibility. This would significantly reduce the size of the APK. Now, it's also necessary to address the issue of the extraction time of app.zip when it's very large; this could take minutes.

**Comment by certainlyWrong** [comment]
> > Olá, estou lutando com o mesmo problema. 
> > Por exemplo, adicionar 'plyer' a require.txt e usá-lo em main.py funciona bem, mas adicionar 'numpy==1.24.2' leva a um SocketError (nenhum arquivo ou diretório) durante a execução do aplicativo.
> 
> no Android você pode usar pacotes de extensões C como numpy, cv2, tflite, pandas, tensoflow, pytouch ... o que você precisa fazer é usar python3.8. A imagem acima é um exemplo
> 
> ![Captura de tela_2023-08-27-17-54-45-086_com.example.example.jpg](https://user-images.githubusercontent.com/103344064/265221138-48fd3d4e-8fa3-4a6e-9358-a2557ee1b535.jpg)

What do I need to do to change the Python version?

**Comment by FeodorFitsner** [comment]
Here is how you can add 3rd-party libraries to your app with serious_python: https://github.com/flet-dev/serious-python/tree/main/src/serious_python#adding-custom-python-libraries
