### ISSUE TITLE
Maybe a bug

### ISSUE THREAD

**Issue by AdamMusa** [flet-dev/serious-python#16]
Hello, I want to run flet app inside the flutter application using serious_python but I got this error
 
<img width="685" alt="Capture d’écran 2023-08-15 à 10 59 22" src="https://github.com/flet-dev/serious-python/assets/37194177/d7a6251c-07c0-417c-9059-edffb913b80c">

Here is  my emulator device 

<img width="1360" alt="Capture d’écran 2023-08-15 à 10 56 40" src="https://github.com/flet-dev/serious-python/assets/37194177/d86df54e-5ccb-4a03-b7db-28cfa2c28f2e">

**Comment by FeodorFitsner** [comment]
Thanks for your interest! Could you please run the app from XCode, in debug mode - you should be able to see more descriptive error.

**Comment by AdamMusa** [comment]
Here is the app run in Xcode
<img width="1317" alt="Capture d’écran 2023-08-16 à 00 08 22" src="https://github.com/flet-dev/serious-python/assets/37194177/33d13a69-352c-40b6-87ac-25c2f1ded388">

**Comment by FeodorFitsner** [comment]
It doesn't look like you are running with the latest version of serious_python. Can you upgrade to 0.2.3 and try again?

**Comment by AdamMusa** [comment]
I have already the latest  version of serious_python
<img width="960" alt="Capture d’écran 2023-08-16 à 08 29 11" src="https://github.com/flet-dev/serious-python/assets/37194177/74f7ea0d-e107-4f1a-8cf3-4bf2437b1fc4">
