### ISSUE TITLE
Error connecting to Flet server

### ISSUE THREAD

**Issue by MatheusRocha-CyberP23** [flet-dev/serious-python#17]
Hello, I'm a little newbie in these issues, I performed the following steps, 

- I created a folder called app and inside that folder another called src in the project roots
- I added a main.py file inside the app/src folder,
- I executed the command **'dart run serious_python:main package app/src'**
    which gave me the following message: 
        Building package executable...
        Built serious_python:main.
        Deleting C:\Users\mathg\AppData\Local\Temp\serious_python_temp7915e2ca\main.py
        and a zip file called app.zip was created **NOTE: there was nothing inside the zip file.**

- I copied the examples from flet_example etc...

and when I run the project I get the following error:
![imagem_2023-08-15_230212044](https://github.com/flet-dev/serious-python/assets/121207419/e9e1c725-3a75-4958-bdfb-d4654961dc8c)

Did I do something wrong in the process? Thanks in advance.

**Comment by FeodorFitsner** [comment]
Are you running packaging command on Windows?

**Comment by MatheusRocha-CyberP23** [comment]
Hi @FeodorFitsner, 
Yes. I'm using Windows 11.

**Comment by larsien** [comment]
@MatheusRocha-CyberP23 
When you open the pubspec.yaml then you can find 
`
assets:
    - app/app.zip
`
How about to make the zip file manually?

**Comment by MatheusRocha-CyberP23** [comment]
Hi @larsien,
After a few attempts, I managed to run the command and the .zip file was created with the main.pyc file inside, however when trying to run the error of connecting to the flet server still persists...
![imagem_2023-08-16_031425467](https://github.com/flet-dev/serious-python/assets/121207419/6d2610be-0122-46f7-884b-53402403c7c5)

**Comment by larsien** [comment]
flutter sdk 3.10.5 occur same error. Please help ! 
![스크린샷 2023-08-19 오전 1 32 55](https://github.com/flet-dev/serious-python/assets/4662566/26bd108c-db0e-42b2-b5e2-1398664efe63)

**Comment by Hindrich0815** [comment]
For me this error only occours when i add for example 'numpy' to requirements.txt and importing it to main.py.
But importing 'plyer' works fine tho...

**Comment by PedroRozadas** [comment]
I have this issue using this flet_example, i'm trying to deploy in android. https://github.com/flet-dev/serious-python/tree/main/src/serious_python/example/flet_example
![Code_ERIasWeyOP](https://github.com/flet-dev/serious-python/assets/88454738/a07fa24b-9716-4f96-ab92-a6ade1dfae57)

**Comment by PedroRozadas** [comment]
https://discord.com/channels/981374556059086931/1161593594780581938 the error I have with the flet server is related to the version of andriod, in my case 7.1.2
