### ISSUE TITLE
Kill python application

### ISSUE THREAD

**Issue by SKbarbon** [flet-dev/serious-python#22]
I am using this package in non-flet purposes. Im facing a need of stopping/killing the python process. Is there a way or a planned way to do this? Its highly recommended because using "sys.exit()" or "os._exit()" is actually exiting the whole flutter app.

**Comment by du9ngtdh** [comment]
> I am using this package in non-flet purposes. Im facing a need of stopping/killing the python process. Is there a way or a planned way to do this? Its highly recommended because using "sys.exit()" or "os._exit()" is actually exiting the whole flutter app.

cPython.Py_Finalize();
Please publicize the cPython object from serious_python

**Comment by FeodorFitsner** [comment]
I don't think "killing" Python process is a proper way to deal with that. serious_python runs Python in-process.
You would need a way to communicate from Dart to Python that you'd like Python program to finish, like pipes, sockets.
Take a look at Flet and `flet_example` - Flet starts a socket server on Python side and then connects to it from Dart.
