### ISSUE TITLE
Android on the same level as windows?

### ISSUE THREAD

**Issue by Bogdantuz** [flet-dev/serious-python#23]
How are the developments regarding 'Embeddable Python for desktop Flutter apps (in the order of priority): macOS, Windows, Linux' progressing?

**Comment by FeodorFitsner** [comment]
macOS, Windows and Linux support are almost done!
Look, end-to-end Flet app test using serious_python running on all platforms: https://ci.appveyor.com/project/flet-dev/serious-python/builds/48375343

Closing in favour of #29.
