### ISSUE TITLE
Dead link in description

### ISSUE THREAD

**Issue by gabboraron** [flet-dev/serious-python#28]
Hi on the website https://flet.dev/blog/flet-for-android/ this link is not working: https://flet.dev/blog/flet-for-android/

**Comment by FeodorFitsner** [comment]
Sorry, but it's a working link. I cannot reproduce the issue.

**Comment by gabboraron** [comment]
![Screenshot from 2023-10-15 23-44-01](https://github.com/flet-dev/serious-python/assets/24356938/4ad2fb16-9c3a-44ea-8d37-d0b8d1c62349)
