### ISSUE TITLE
Add macOS support

### ISSUE THREAD

**Issue by cbenhagen** [flet-dev/serious-python#3]
What are your plans to package the Python runtime as well as custom libraries on macOS? Will it also be similar to what Kivy does? Or maybe using PythonKit?

**Comment by FeodorFitsner** [comment]
Sure, we are going to support macOS right after Android! Currently, the plan is utilize [kivy-sdk-packager](https://github.com/kivy/kivy-sdk-packager/tree/master/osx) project to build embeddable Python framework.

**Comment by FeodorFitsner** [comment]
Closing in favour of #29
