### ISSUE TITLE
App packaging command not including app file

### ISSUE THREAD

**Issue by tnghieu** [flet-dev/serious-python#31]
When running:
`dart run serious_python:main package app/src
`

It creates the app.zip file, when opening the file to examine the contents, I only see the requirements.txt file.

This happens with my project and also with the example [flask example](https://github.com/flet-dev/serious-python/tree/main/src/serious_python/example/flask_example) provided by serious-python

Is this expected? 

I get this error when running SeriousPython.run("assets/app/app.zip")

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unable to load asset: "app/app.zip".
The asset does not exist or has empty data.

**Comment by FeodorFitsner** [comment]
What OS are you packaging the zip on? Can you provide a full log of packaging command?

**Comment by tnghieu** [comment]
I am developing on a Mac, developing for Android/iOS.

This is the output after running the packaging command:

Building package executable... 
Built serious_python:main.
Deleting /var/folders/q5/wnpg1myn15z9_409ndfx_4vw0000gn/T/serious_python_tempjD02Eb/src/main.py

**Comment by FeodorFitsner** [comment]
Is it entire log you get? What version of serious_python is that?

**Comment by tnghieu** [comment]
I've determined that the issue is that one of the packages are failing to install. After diving deeper, I need to manually load this package into the packages directory.

Where can I find this directory to place this package?

**Comment by FeodorFitsner** [comment]
It should be inside `app/__pypackages__`.

**Comment by tnghieu** [comment]
When running (dart run serious_python:main package assets/app/src), it starts to collect packages from requirements.txt.

One of those packages are failing and I think I need a way to have the package installed already.

Is it correct that __pypackages__ is created after a successful dart run serious_python....
