### ISSUE TITLE
dart run serious_python:main package app/src - not working

### ISSUE THREAD

**Issue by Aporial** [flet-dev/serious-python#49]
![1](https://github.com/flet-dev/serious-python/assets/7197773/0cf73822-2c95-4007-804a-825e2aeb3df0)

dart run serious_python:main package app/src does not work. stops at installing dependencies. Even if you just leave the flet module, it will still freeze. this morning everything worked fine

**Comment by FeodorFitsner** [comment]
serious_python package was updated 5 days ago, not this morning. I bet pip is having a problem downloading some packages. Try adding `--verbose` to the command to see its progress/output.

**Comment by Aporial** [comment]
> Пакет ozbiljan_пітон оновлено 5 днів тому, а не сьогодні вранці. Б’юся об заклад, що у pip є проблема із завантаженням деяких пакунків. Спробуйте додати `--verbose`до команди, щоб побачити її прогрес/вихід.

![image](https://github.com/flet-dev/serious-python/assets/7197773/dd23047f-235f-44de-a4ef-71947ef1a6da)

I left only flet in the dependencies. and also added `--verbose`

**Comment by FeodorFitsner** [comment]
What OS is that?

Also, try deleting that `...hostpython3.11\python` directory.

**Comment by Aporial** [comment]
> What OS is that?
> 
> Also, try deleting that `...hostpython3.11\python` directory.

Windows 10 Pro 22H2.


Thank you very much. Deleting the folder `...hostpython3.11\python` helped!
