### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by emirhalici** [flet-dev/serious-python#5]
Is there a *rough* timeline on Android support? For iOS it seems you're using kivy. What will you do with Android?

**Comment by FeodorFitsner** [comment]
Thanks for your interest! I've been looking at Kivy for Android and it looks pretty up-to-date with a bunch of popular recipes available. Will hopefully have add Android support by the end of summer.

**Comment by FeodorFitsner** [comment]
Android has been supported.
