### ISSUE TITLE
runProgram causes android crash

### ISSUE THREAD

**Issue by khaven** [flet-dev/serious-python#57]
Hi,
I'm trying to create a python script file and run the file using the `SeriousPython.runProgram` function but it causing the android to crash. Here's my code:
```
File file = await File(p.join((await getApplicationDocumentsDirectory()).path, 'myfile.py')).create(recursive: true);

file.writeAsStringSync('print("hello world")', flush: true);

Directory.current = p.dirname(file.path);

print(file.path);

String? out = await SeriousPython.runProgram(file.path, environmentVariables: {"a": "1", "b": "2"},  sync: true);

print(out);
```

Here's the console output:
![Capture](https://github.com/flet-dev/serious-python/assets/16809913/6a682dc9-4e7c-4cb0-b0f8-230ff7e8568a)

**Comment by FeodorFitsner** [comment]
Oh, it's x86_64 architecture. What kind of device is that?

**Comment by FeodorFitsner** [comment]
I have no idea, why it's crashing with null pointer, but it happens on x86_64 architecture. I don't know if it's on specific or all devices, but that was the reason we disabled x86_64 arch for Flet app in Google Play.

I guess this is relevant CPython code:
https://github.com/python/cpython/blob/3.11/Python/import.c#L1996
https://github.com/python/cpython/blob/3.11/Objects/listobject.c#L155

How to debug that? I don't have much C experience 🥹

**Comment by FeodorFitsner** [comment]
It works on x86_64 Android simulator though: https://ci.appveyor.com/project/flet-dev/serious-python/build/job/o8j1f3wm73qdjb56#L373

**Comment by khaven** [comment]
I don't know what I did wrong. But after creating a new project, the code is working fine on the same Android emulator. I wish it returned "hello world" instead of "null" though. I was testing the code on the flask example before. Thank you for your help :)

**Comment by FeodorFitsner** [comment]
OK, thanks for the update. I don't like that sporadic error though.
I'm working right now on catching output. It's going to be for Android first.

**Comment by khaven** [comment]
I'm so excited to hear that! Thanks again. I'm closing this issue.
