### ISSUE TITLE
unable to add youtube-dl package

### ISSUE THREAD

**Issue by imgarvish** [flet-dev/serious-python#59]
i successfully installed and utilized a sample flask application. however, complications arise upon integrating the yt_dlp module, leading to a severe crash in the application.

here's the log:
<img width="928" alt="Screenshot 2024-01-15 at 1 46 32 AM" src="https://github.com/flet-dev/serious-python/assets/89016084/81de8ad1-c084-4947-8f59-0f947d01614f">

EDIT:

adding more logs:
<img width="927" alt="Screenshot 2024-01-15 at 1 54 53 AM" src="https://github.com/flet-dev/serious-python/assets/89016084/f16626b9-e0fa-4682-b012-eb8476d4bbf5">

let me know if there's anything else that i can provide.

**Comment by FeodorFitsner** [comment]
Provide a repro app please?

**Comment by imgarvish** [comment]
app is almost same as flask_example.

just change main.py file to:
```
from contextlib import redirect_stdout
from io import StringIO

from flask import Flask, request
import yt_dlp

port = 55001

print("Trying to run a socket server on:", port)


class PythonRunner:
    __globals = {}
    __locals = {}

    def run(self, code):
        f = StringIO()
        with redirect_stdout(f):
            exec(code, self.__globals, self.__locals)
        return f.getvalue()


pr = PythonRunner()


app = Flask(__name__)


@app.route("/")
def hello_world():
    try:
        info = yt_dlp.YoutubeDL({
            "format": "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best"
        }).extract_info("https://www.youtube.com/watch?v=XV1fpQSObv8&pp=ygUdb2xpdmlhIHJvZHJpZ28gdmFtcGlyZSBseXJpY3M%3D", download=False)
        return str(info)
    except:
        return "youtuber"


@app.route("/python", methods=["POST"])
def run_python():
    try:
        return pr.run(request.json["command"])
    except Exception as e:
        return str(e)

app.run(port=port, debug=True)

```

**Comment by imgarvish** [comment]
@FeodorFitsner is it reproducible or should i provider more info?

**Comment by FeodorFitsner** [comment]
`yt_dlp` has a bunch of native (non-pure) dependencies: `pycryptodomex`, `websockets`, `Brotli`, `charset_normalizer`:

```
Collecting yt_dlp
  Downloading yt_dlp-2023.12.30-py2.py3-none-any.whl (3.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 27.3 MB/s eta 0:00:00
Collecting mutagen
  Downloading mutagen-1.47.0-py3-none-any.whl (194 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.4/194.4 kB 13.0 MB/s eta 0:00:00
Collecting pycryptodomex
  Downloading pycryptodomex-3.20.0-cp35-abi3-macosx_10_9_universal2.whl (2.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 70.5 MB/s eta 0:00:00
Collecting certifi
  Using cached certifi-2023.11.17-py3-none-any.whl (162 kB)
Collecting requests<3,>=2.31.0
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting urllib3<3,>=1.26.17
  Using cached urllib3-2.1.0-py3-none-any.whl (104 kB)
Collecting websockets>=12.0
  Downloading websockets-12.0-cp311-cp311-macosx_11_0_arm64.whl (121 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.3/121.3 kB 14.1 MB/s eta 0:00:00
Collecting brotli
  Downloading Brotli-1.1.0-cp311-cp311-macosx_10_9_universal2.whl (873 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 873.1/873.1 kB 46.2 MB/s eta 0:00:00
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.3.2-cp311-cp311-macosx_11_0_arm64.whl (118 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.6-py3-none-any.whl (61 kB)
Installing collected packages: brotli, websockets, urllib3, pycryptodomex, mutagen, idna, charset-normalizer, certifi, requests, yt_dlp
Successfully installed brotli-1.1.0 certifi-2023.11.17 charset-normalizer-3.3.2 idna-3.6 mutagen-1.47.0 pycryptodomex-3.20.0 requests-2.31.0 urllib3-2.1.0 websockets-12.0 yt_dlp-2023.12.30
```

Kivy doesn't have Android recipes for them.

Without compiling those modules for Android the app won't work.

**Comment by imgarvish** [comment]
thanks for your investigation! i will close this issue now.

also thanks a lot for maintaining the package. it helps use flutter devs to use the power of python and it's within out apps ;)

**Comment by imgarvish** [comment]
also can you name some other ways i can use youtube-dl and other packages with flask specially? i would love to explore them my own.

**Comment by FeodorFitsner** [comment]
I'd recommend creating an API server (Flask, FastAPI) and move parts that cannot be run on mobile there. Then use any REST lib to access API server from a mobile app.

**Comment by imgarvish** [comment]
the problem with that is that if my server is in different location from where the user is making the request then due to region (country) differences they can't download the url fetch by the server.

gives 403 forbidden error on the user side.

i wonder how those youtube video downloader app achieve this!?

**Comment by imgarvish** [comment]
also see how this ios swift library achieves the same thing [YoutubeDL-iOS](https://github.com/kewlbear/YoutubeDL-iOS)

**Comment by hieulbp** [comment]
@heygarvish Have you successfully run yt-dlp on android and ios?
