### ISSUE TITLE
seriouspython.run fails with strange python exception

### ISSUE THREAD

**Issue by WhiteGobo** [flet-dev/serious-python#64]
When running the python script with `SeriousPython.run`, flutter fails with the error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'null' is not defined
```

<details><summary>more details</summary>
Running on linux.
python files are organized this way: 

```
app/
  app.zip
  src/
    __init__.py
    main.py
```

command as used in dart:

```
...
await SeriousPython.run("app/app.zip",
    appFileName: "main.py",
);
...
```

The asset `app/app.zip` was declared in `pubspec.yaml`:

```
(...)
flutter:
  uses-material-design: true
  assets:
    - app/app.zip
```

verbose output of the error:

```
[  +32 ms] flutter: Start unpacking app archive
[  +18 ms] flutter: Finished unpacking application archive.
[  +11 ms] modulePaths joined string:
/tmp/test_python-1.0.0-1/app:/tmp/test_python-1.0.0-1/app/__pypackages__:/home/
hfechner/Projects/fluttergettingstarted/test_python/build/linux/x64/debug/bundl
e/python3.11:/home/hfechner/Projects/fluttergettingstarted/test_python/build/li
nux/x64/debug/bundle/python3.11/site-packages
[        ] exe_dir:
/home/hfechner/Projects/fluttergettingstarted/test_python/build/linux/x64/debug
/bundle
[        ] app_dir: /tmp/test_python-1.0.0-1/app
[        ] sync: false
[        ] Traceback (most recent call last):
[        ]   File "<string>", line 1, in <module>
[        ] NameError: name 'null' is not defined
```

The python stuff could be located in a temporary directory:
```
ls /tmp/test_python-1.0.0-1/app/
>> __init__.pyc  main.pyc
```

</details>

**Comment by WhiteGobo** [comment]
It seems that despite `script` being some kind of `null`, serious-python tries to load a script in line 158:   
https://github.com/flet-dev/serious-python/blob/1b7cdbd6252a897d1a326cf3d4cb250e1690cdbd/src/serious_python_linux/linux/serious_python_linux_plugin.cc#L156-L160

**Comment by jifalops** [comment]
i'm getting this with the run_example and flask_example on linux.

**Comment by jifalops** [comment]
@WhiteGobo I tried a few things like setting `appFileName` and `sync: true` in main.dart of the run_example. I think the error occurs from `fl_value_to_string(script)`. I don't think the value of `script` was ever a `nullptr` when I was changing things.

**Comment by WhiteGobo** [comment]
Yeah another fix qould be to replace:

https://github.com/flet-dev/serious-python/blob/e44dff11516019060d4e37e7a4ab900750c0243c/src/serious_python_linux/lib/serious_python_linux.dart#L30-L37

with this:

```
   Map<String, dynamic> arguments = {
      'exePath': Platform.resolvedExecutable,
      'appPath': appPath,
      'modulePaths': modulePaths,
      'environmentVariables': environmentVariables,
      'sync': sync
    };
    if (script != null) {arguments['script'] = script;}
```

But it did seem like a clear problem coming from flutter and not from serious-python. But i didnt had time/forgot later to open up an issue there.

**Comment by jifalops** [comment]
Yes that will work and is more direct. The problem seems to be that the type `String?` is encoded to `'null'` when null. A brief search on the internet didn't find more complaints about this, but they're surly out there.
