### ISSUE TITLE
Windows build error

### ISSUE THREAD

**Issue by RA341** [flet-dev/serious-python#70]
trying to build for windows

I get

```
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\include\format(42): warning STL4038: The contents of <format> are available only with C++20 or later. [<my project path>/build\windows\x64\plugins\serious_python_windows\serious_python_windows_plugin.vcxproj]
```

and then

```
Syncing files to device Windows...
flutter: Start unpacking app archive
flutter: Finished unpacking application archive.
Lost connection to device.
```

it will not build on windows and keeps crashing

not sure whats happening here

**Comment by jackie099** [comment]
Same issue,

It builds fine, runs but crashes immediately after loading

**Comment by jackie099** [comment]
Update: 

Found the issue after running with VS debugger, platform channel messager is looking for script variable even it's nullable

For now, you can modify serious_python.dart and modify line 64:
Give script an empty string

`    return runProgram(appPath,
        modulePaths: modulePaths,
        environmentVariables: environmentVariables,
        script: "",
        sync: sync);`

**Comment by rajputs37** [comment]
PR raised here https://github.com/flet-dev/serious-python/pull/83
Thanks @jackie099
