### ISSUE TITLE
Is spaCy supported?

### ISSUE THREAD

**Issue by jifalops** [flet-dev/serious-python#73]
There isn't a recipe in the [official repo](https://github.com/kivy/python-for-android/tree/develop/pythonforandroid/recipes), but I found this [two year old recipe](https://github.com/F1uctus/p4a-recipes/blob/main/spacy/__init__.py). I'm new to python-4-android but the other platforms seem like they'll work with serious-python.

**Comment by baseplate-admin** [comment]
This discussion should be on `python-for-android`, not here

**Comment by jifalops** [comment]
Thanks, I've asked in their support channel a couple of times but no answer. 

Are you aware of anyone using serious-python with spaCy? My goal is to offline event extraction on mobile and desktop. The small (12MB) model from spacy does really well in my testing.

**Comment by baseplate-admin** [comment]
> Thanks, I've asked in their support channel a couple of times but no answer.

I understand your frustration. `kivy` team is lacking the manpower to move the entire ecosystem forward. Only 1 person managing everything.

> Are you aware of anyone using serious-python with spaCy? My goal is to offline event extraction on mobile and desktop. The small (12MB) model from spacy does really well in my testing.

I am really sorry, but i never used `spaCy` with neither `kivy` nor `flet`. I think raising an issue to support `spaCy` in `python-for-android` issue is the way to move forward.
