### ISSUE TITLE
Packaging python app using the packaging command raising an error on windows

### ISSUE THREAD

**Issue by russell-white** [flet-dev/serious-python#8]
When using the packaging command:
"dart run serious_python:main package app/src"

There is an error in windows as following:
Python has already downloaded to C:\Users\itsru\AppData\Local\Temp\hostpython3.10

I did these stuff correctlly:
- Creating a main.py file inside the "src" of "app" folder.
- Put "app" in the root.
- Call the command, then the error raise.

**Comment by FeodorFitsner** [comment]
Can you do a screenshot please?

**Comment by russell-white** [comment]
Yes 
![Screenshot 2023-07-30 204904](https://github.com/flet-dev/serious-python/assets/128521274/6c51a922-a029-4584-ba38-22843a38e321)

**Comment by russell-white** [comment]
@FeodorFitsner 
![Screenshot 2023-07-30 204904](https://github.com/flet-dev/serious-python/assets/128521274/24bf9d8e-a469-4934-89e9-b0a99e1a205c)
