### ISSUE TITLE
Are custom packages supported for Android?

### ISSUE THREAD

**Issue by tanishbajaj101** [flet-dev/serious-python#81]
This was mentioned in main GitHub page
I wanted to ask whether those with recipes are supported for Android or not

_All "pure" Python packages are supported. These are packages that implemented in Python only, without native extensions written in C, Rust or other low-level language.

For iOS: packages with native extensions having a [recipe](https://github.com/kivy/kivy-ios/tree/master/kivy_ios/recipes) are supported. To use these packages you need to build a custom Python distributive for iOS (see below)._

**Comment by FeodorFitsner** [comment]
That's correct.
