### ISSUE TITLE
Cannot run on MacOS

### ISSUE THREAD

**Issue by HighLiuk** [flet-dev/serious-python#90]
If I try to run the (example) flutter app on MacOS I get

“_speedups.cpython-311-darwin.so” cannot be opened because the developer cannot be verified.

<img width="825" alt="Screenshot 2024-05-25 at 08 54 06" src="https://github.com/flet-dev/serious-python/assets/65017775/7939ebf0-f878-402f-9c9a-d048dd6c6c47">

and then the app stops working. Also, if I restart the app, it quits.

**Comment by FeodorFitsner** [comment]
Make sure the app is not running in sandbox mode (check entitlements).

**Comment by HighLiuk** [comment]
Yep now it's fixed as explained in #42
