### ISSUE TITLE
Where should I put requirements.txt file on MacOS?

### ISSUE THREAD

**Issue by QuanchaoSong** [flet-dev/serious-python#99]
Hi, I am going to run this example on MacOS, and I try to add a custom library `numpy`. But I don't know where to put that file.

Which place should I put it?

<img width="1588" alt="Screenshot 2024-06-21 at 2 23 36 PM" src="https://github.com/flet-dev/serious-python/assets/47345588/bed41ab5-23bb-469f-8df3-e2a3604c6e72">

**Comment by FeodorFitsner** [comment]
Is no longer relevant as packaging command does not require requirements.txt anymore.
